---
- name: Deploy das máquinas físiscas
  include: 1-host/host.yml

- name: Criação das máquinas virtuais
  include: 2-guest/1-vagrant-up.yml

- name: Deploy das máquinas virtuais
  include: 2-guest/3-guest.yml

- name: Reload das máquinas virtuais
  include: 2-guest/4-vagrant-reload.yml

- name: Deploy do cluster Kubernetes
  include: 3-cluster/cluster.yml

- name: Deploy do container
  include: 4-container/container.yml